
{{- if .Values.global.steampipeCreateReadOnlyServiceAccount }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: steampipe-sa-role
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
rules:
  - apiGroups: ["*"]  # All API groups
    resources: ["*"]  # All resources
    verbs: ["get", "list", "watch"]  # Read-only permissions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: steampipe-sa-role-binding
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "steampipe.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::115048773353:role/dev-steampipe-external-secrets-role
roleRef:
  kind: ClusterRole
  name: steampipe-sa-role
  apiGroup: rbac.authorization.k8s.io
{{- end }}