apiVersion: v1
kind: Secret
metadata:
  name: {{ include "steampipe.fullname" . }}-secret-env-vars
  labels:
    {{- include "steampipe.labels" . | nindent 4 }}
stringData:
  STEAMPIPE_DATABASE_PASSWORD: {{ .Values.global.steampipeDatabasePassword }}
  PGDATABASE: "steampipe"
  PGHOST: "0.0.0.0"
  PGPASSWORD: {{ .Values.global.steampipeDatabasePassword }}
  PGUSER: "steampipe"
  PGPORT: "9193"
